"""add poster column to movies table

Revision ID: d40d2afa67f3
Revises: 59cf6a80bc33
Create Date: 2025-09-18 14:04:47.501086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40d2afa67f3'
down_revision: Union[str, Sequence[str], None] = '59cf6a80bc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster')
    # ### end Alembic commands ###
